import { useEffect, useRef, useMemo } from "react";
import type { AcceptableTarget, CorePiece, MountPiece } from "@collagejs/core";
import { mountPiece } from "@collagejs/core";
import { useCollageContext } from "./collageContext.js";
import { CorePieceLcQueue, hostAttributes, unmountAndTransferLcQueue } from "@collagejs/adapter";
import type { PieceOptions } from "./types.js";

/**
 * Symbol used to store the Piece component's own properties.  This doesn't reserve any public prop names so the entire 
 * namespace can be used for the mounted core piece object.
 */
const piecePropsSymbol = Symbol("collagejs.pieceProps");
/**
 * Special props consumed by the React `Piece` component.
 *
 * This type is meant to be combined with regular piece props through the
 * `piece()` helper. The symbol-backed key keeps the internal mount metadata
 * out of the public prop namespace, so user props can use any string key
 * without collisions.
 */
type PieceProps<TProps extends Record<string, any> = Record<string, any>> = {
    [piecePropsSymbol]: PieceOptions & {
        /**
         * The required core piece instance (or promise) to mount.
         */
        piece: CorePiece<TProps> | Promise<CorePiece<TProps>>;
    };
};
/**
 * Creates the special symbol-backed prop required by the `Piece` component.
 *
 * Spread the returned object into `<Piece />` props.
 *
 * @example
 * ```tsx
 * <Piece {...piece(myCorePiece, { containerProps: { className: "host" }, shadow: true })} foo="bar" />
 * ```
 *
 * @param piece CorePiece instance (or promise) to mount.
 * @param options Optional settings for the host `<div>` and shadow-root behavior.
 */
export function piece<TProps extends Record<string, any> = Record<string, any>>(
    piece: CorePiece<TProps> | Promise<CorePiece<TProps>>,
    options?: PieceOptions,
) {

    return {
        [piecePropsSymbol]: {
            piece,
            ...options,
        },
    } as PieceProps<TProps>;
}
/**
 * Property key used to store the shadow root on the container element.
 * @internal
 */
const containerShadowKey = Symbol();
/**
 * Obtains the target where the core piece should mount based on the current shadow configuration.
 * 
 * **ℹ️ NOTE**:  Because of React's [Strict Mode](https://react.dev/reference/react/StrictMode), the function provided
 * by `@collagejs/adapter` cannot be used:  Strict mode runs top-level rendering code twice, but doesn't destroy the 
 * markup generated by the first one.  The container is the same, which causes the provided function to throw trying
 * to create a shadow root on an element that already has one.
 * 
 * This function attaches the shadow root to the container using a symbol property, and uses this property first before
 * trying to create shadow roots.
 * @param container Container for the core piece.
 * @param shadow Current shadow configuration.
 * @returns The target where the core piece needs to mount according to the current shadow configuration.
 */
function getPieceTarget(container: HTMLDivElement, shadow: boolean | ShadowRootInit): AcceptableTarget {
    if (shadow === false) {
        return container;
    }
    const shadowMode = shadow === true ? "open" : shadow.mode;
    const existingShadow = (container as any)[containerShadowKey] as ShadowRoot | undefined;
    if (existingShadow && existingShadow?.mode !== shadowMode) {
        throw new Error(`Shadow root mode mismatch:  Existing shadow root has mode "${existingShadow?.mode}", but requested mode is "${shadowMode}".  It's impossible to comply.`);
    }
    if (existingShadow) {
        return existingShadow;
    }
    const init = shadow === true ? { mode: "open" as const } : shadow;
    const newRoot = container.attachShadow(init); 
    (container as any)[containerShadowKey] = newRoot;
    return newRoot;
}

function PieceImpl<TProps extends Record<string, any> = Record<string, any>>(
    props: TProps & PieceProps<TProps>,
) {
    const { [piecePropsSymbol]: pieceProps, ...restProps } = props;
    const logger = useMemo(() => (pieceProps.logging ? console : undefined), [pieceProps.logging]);
    logger?.group('Piece Render');
    const containerRef = useRef<HTMLDivElement>(null);
    const containerRefChg = useRef(containerRef.current);
    logger?.debug('[Piece] Container Ref changed?', containerRefChg.current !== containerRef.current);
    containerRefChg.current = containerRef.current;
    /**
     * Tracks the current mount target (either the container div or a shadow root) for the mounted piece.
     */
    const mountTargetRef = useRef<AcceptableTarget | null>(null);
    /**
     * Variable to make TS happy.  Doesn't seem to be capable of knowing that symbol is no longer in the type.
     */
    const cpProps = restProps as unknown as TProps;
    /**
     * Shadow setting with default applied.
     */
    const shadow = pieceProps.shadow ?? false;
    /**
     * The mountPiece function to use by the LC queue.
     */
    const parentAwareMountPieceFn = useCollageContext();
    const mountPieceFn = useMemo(() => (parentAwareMountPieceFn ?? mountPiece) as MountPiece<TProps>, [parentAwareMountPieceFn]);
    /**
     * Key used for the root element to force remounting when the shadow setting changes.
     */
    const rootElKey = (() => {
        switch (shadow) {
            case false:
                return "light";
            case true:
                return "open";
            default:
                return shadow.mode;
        }
    })();
    /**
     * LC queue for managing the lifecycle of the mounted piece.
     */
    const lc = useRef(new CorePieceLcQueue(pieceProps.piece, mountPieceFn));

    logger?.debug('[Piece] Container:', containerRef.current);
    logger?.debug('[Piece] Mount Target:', mountTargetRef.current);
    logger?.debug('[Piece] Shadow setting:', shadow);
    logger?.debug('[Piece] Root Key:', rootElKey);
    logger?.debug('[Piece] Core Piece Props:', cpProps);
    logger?.debug('[Piece] LC Queue:', lc.current);
    
    // useImperativeHandle(ref, () => containerRef.current as HTMLDivElement);

    // Unmount, transfer & mount.
    useEffect(() => {
        if (!mountTargetRef.current) {
            logger?.debug('[Piece] useEffect triggered for unmount/transfer/mount, but mount target is not available yet.');
            return;
        }
        logger?.debug('[Piece] useEffect triggered for unmount/transfer/mount. Piece:', pieceProps.piece);
        lc.current = unmountAndTransferLcQueue(lc.current, pieceProps.piece, mountPieceFn);
        lc.current.mount(mountTargetRef.current, cpProps);
    }, [parentAwareMountPieceFn, pieceProps.piece]);

    // Mount.
    useEffect(() => {
        if (!containerRef.current) {
            logger?.debug('[Piece] useEffect triggered for mounting, but container is not available yet.');
            return;
        }
        containerRefChg.current = containerRef.current;
        logger?.debug('[Piece] useEffect triggered for mounting.');
        mountTargetRef.current = getPieceTarget(containerRef.current, shadow);
        lc.current.mount(mountTargetRef.current, cpProps);

        return () => {
            logger?.debug('[Piece] useEffect cleanup triggered for unmounting.');
            mountTargetRef.current = null;
            lc.current.unmount();
        };
    }, []);

    // Relocate.
    useEffect(() => {
        if (!containerRef.current || !mountTargetRef.current) {
            logger?.log('[Piece] useEffect triggered for relocating, but container or mount target is not available yet.');
            return;
        }
        logger?.debug('[Piece] useEffect triggered for relocating.  Shadow:', shadow);
        const newTarget = getPieceTarget(containerRef.current, shadow);
        if (newTarget === mountTargetRef.current) {
            logger?.debug('[Piece] Relocate useEffect: new target is the same as current target. No action taken.');
            return;
        }
        lc.current.relocate(mountTargetRef.current, newTarget, cpProps);
        lc.current.enqueue(() => void (mountTargetRef.current = newTarget));
    }, [shadow]);

    // Update.
    useEffect(() => {
        logger?.debug('[Piece] useEffect triggered for updating. CP Props:', cpProps);
        lc.current.update(cpProps);
    }, [cpProps]);
    logger?.groupEnd();

    return (
        <div
            key={rootElKey}
            ref={containerRef}
            {...pieceProps.containerProps}
            {...hostAttributes({ framework: "react", shadow })}
        />
    );
}
/**
 * ### Piece Component
 * 
 * The `Piece` component is a React wrapper for mounting *CollageJS* pieces. It manages the lifecycle of the piece, 
 * including mounting, updating, relocating, and unmounting, while providing a container for the piece to render into.
 * The component supports both light DOM and shadow DOM rendering based on the provided options.
 * 
 * @example
 * ```tsx
 * function AppComponent() {
 *   import { useMemo, useState } from "react";
 *   import { Piece, piece } from "@collagejs/react";
 *   import { myCorePiece } from "@myScope/myCorePiece";
 * 
 *   const myPiece = useMemo(() => myCorePiece(), []);
 *   const [pieceProps, setPieceProps] = useState({ foo: "bar", count: 0 });
 * 
 *   return <>
 *     <Piece
 *       {...piece(myPiece, { containerProps: { className: "host" }, shadow: true })}
 *       {...pieceProps}
 *     />
 *     <button
 *       onClick={() => setPieceProps({ ...pieceProps, count: pieceProps.count + 1 })}
 *     >
 *       Increment Count
 *     </button>
 *   </>;
 * }
 * ```
 * 
 * **ℹ️ IMPORTANT**:  The actual core piece (or the promise to it) should be memoized.
 */
export const Piece = PieceImpl;
